import { useState, useEffect } from 'react';
import { useParams, Link, useOutletContext, useNavigate } from 'react-router-dom';
import Header from '../components/Header';
import ReusabilityBadge from '../components/ReusabilityBadge';
import { useAuth } from '../context/AuthContext';
import { fetchAssetById, deleteAsset, fetchComments, postComment, removeComment, toggleFavorite, rateAsset, fetchRatings, checkMISRACompliance } from '../services/api';
import {
  ArrowLeft, Star, Download, Eye, Clock, User,
  GitBranch, Code2, FileText, Copy, CheckCircle2, Tag, Shield, Loader2,
  Trash2, X, AlertTriangle, Heart, MessageSquare, Send, ShieldCheck, ShieldAlert, FileDown, Car, Cpu
} from 'lucide-react';

export default function AssetDetail() {
  const { onMenuClick } = useOutletContext();
  const { id } = useParams();
  const navigate = useNavigate();
  const { isAdmin, user } = useAuth();
  const [asset, setAsset] = useState(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [deleting, setDeleting] = useState(false);

  // Comments state
  const [comments, setComments] = useState([]);
  const [commentText, setCommentText] = useState('');
  const [postingComment, setPostingComment] = useState(false);

  // Favorites state
  const [isFavorited, setIsFavorited] = useState(false);
  const [favCount, setFavCount] = useState(0);

  // Ratings state
  const [userRating, setUserRating] = useState(0);
  const [hoverRating, setHoverRating] = useState(0);
  const [avgRating, setAvgRating] = useState(0);
  const [ratingCount, setRatingCount] = useState(0);

  // MISRA compliance state
  const [misraResult, setMisraResult] = useState(null);
  const [misraLoading, setMisraLoading] = useState(false);

  const handleMISRACheck = async () => {
    if (!asset?.code || misraLoading) return;
    setMisraLoading(true);
    try {
      const result = await checkMISRACompliance(asset.code, asset.lang);
      setMisraResult(result);
    } catch {
      setMisraResult({ error: true, overallCompliance: 'Failed', misraScore: 0, violations: [], safetyNotes: ['Could not connect to AI service.'], recommendations: [] });
    }
    setMisraLoading(false);
  };

  // Export as documentation
  const handleExportDoc = () => {
    if (!asset) return;
    const lines = [
      `${'='.repeat(60)}`,
      `ASSET DOCUMENTATION — ${asset.name}`,
      `${'='.repeat(60)}`,
      ``,
      `${'─'.repeat(60)}`,
      `METADATA`,
      `${'─'.repeat(60)}`,
      `Name:       ${asset.name}`,
      `Type:       ${asset.type}`,
      `Language:   ${asset.lang || 'N/A'}`,
      `Category:   ${asset.category || 'N/A'}`,
      `Version:    ${asset.version || '1.0.0'}`,
      `Author:     ${asset.author || 'N/A'}`,
      `Status:     ${asset.status}`,
      `Created:    ${asset.createdAt ? new Date(asset.createdAt).toLocaleString() : 'N/A'}`,
      `Score:      ${asset.score || 'N/A'}%`,
      asset.reusabilityLevel ? `ASIL Level: ${['', 'Production-Ready', 'Verified', 'Reference', 'Deprecated'][asset.reusabilityLevel] || 'N/A'}` : '',
      asset.project ? `Project:    ${asset.project}` : '',
      asset.ecuType ? `ECU Type:   ${asset.ecuType}` : '',
      asset.originalFileName ? `Source File: ${asset.originalFileName}` : '',
      ``,
      `${'─'.repeat(60)}`,
      `DESCRIPTION`,
      `${'─'.repeat(60)}`,
      asset.desc || 'No description.',
      ``,
      `${'─'.repeat(60)}`,
      `TAGS`,
      `${'─'.repeat(60)}`,
      (asset.tags || []).join(', ') || 'None',
      ``,
    ];
    if (asset.code) {
      lines.push(
        `${'─'.repeat(60)}`,
        `SOURCE CODE${asset.originalFileName ? ` (${asset.originalFileName})` : ''}`,
        `${'─'.repeat(60)}`,
        ``,
        asset.code,
        ``
      );
    }
    if (misraResult && !misraResult.error) {
      lines.push(`${'─'.repeat(60)}`, `MISRA & SAFETY COMPLIANCE REPORT`, `${'─'.repeat(60)}`);
      lines.push(`ASIL Level:      ${misraResult.asilLevel || 'N/A'}`);
      lines.push(`MISRA Score:     ${misraResult.misraScore || 0}/100`);
      lines.push(`Compliance:      ${misraResult.overallCompliance}`);
      lines.push(``);
      if (misraResult.violations?.length) {
        lines.push(`Violations:`);
        misraResult.violations.forEach((v, i) => {
          lines.push(`  ${i + 1}. [${v.severity}] ${v.rule}`);
          lines.push(`     ${v.description}`);
          if (v.fix) lines.push(`     Fix: ${v.fix}`);
        });
      }
      lines.push(``);
    }
    lines.push(`${'─'.repeat(60)}`, `Generated by Knowledge Factory — ${new Date().toLocaleString()}`, `${'─'.repeat(60)}`);
    const blob = new Blob([lines.filter(l => l !== '').length > 0 ? lines.join('\n') : lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(asset.name || 'asset').replace(/[^a-zA-Z0-9_-]/g, '_')}_documentation.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDelete = async () => {
    setDeleting(true);
    try {
      await deleteAsset(id);
      navigate('/browse');
    } catch (err) {
      console.error('Delete failed:', err);
      alert('Failed to delete asset. Please try again.');
    } finally {
      setDeleting(false);
      setShowDeleteConfirm(false);
    }
  };

  useEffect(() => {
    fetchAssetById(id)
      .then(data => {
        setAsset(data);
        if (data && user?.username) {
          setIsFavorited((data.favoritedBy || []).includes(user.username));
          setFavCount((data.favoritedBy || []).length);
          const ratings = data.ratings || {};
          if (ratings[user.username]) setUserRating(ratings[user.username]);
          const vals = Object.values(ratings);
          if (vals.length > 0) {
            setAvgRating(Math.round(vals.reduce((a, b) => a + b, 0) / vals.length * 10) / 10);
            setRatingCount(vals.length);
          }
        }
      })
      .catch(() => {})
      .finally(() => setLoading(false));

    fetchComments(id)
      .then(data => setComments(Array.isArray(data) ? data : []))
      .catch(() => {});
  }, [id, user?.username]);

  const handleFavorite = async () => {
    if (!user?.username) return;
    try {
      const result = await toggleFavorite(id, user.username);
      setIsFavorited(result.favorited);
      setFavCount(result.count);
    } catch {}
  };

  const handleRate = async (rating) => {
    if (!user?.username) return;
    try {
      const result = await rateAsset(id, user.username, rating);
      setUserRating(rating);
      setAvgRating(result.avgRating);
      setRatingCount(result.count);
    } catch {}
  };

  const handlePostComment = async () => {
    if (!commentText.trim() || !user?.username) return;
    setPostingComment(true);
    try {
      const comment = await postComment(id, user.username, commentText.trim());
      setComments(prev => [comment, ...prev]);
      setCommentText('');
    } catch {}
    setPostingComment(false);
  };

  const handleDeleteComment = async (commentId) => {
    try {
      await removeComment(commentId);
      setComments(prev => prev.filter(c => c.id !== commentId));
    } catch {}
  };

  const handleDownload = () => {
    if (!asset) return;
    const content = asset.code || asset.desc || '';
    let filename;
    if (asset.originalFileName) {
      filename = asset.originalFileName;
    } else {
      const ext = asset.type === 'Code'
        ? { 'JavaScript': '.js', 'TypeScript': '.ts', 'Python': '.py', 'Java': '.java', 'Go': '.go', 'Rust': '.rs', 'C': '.c', 'C++': '.cpp', 'C#': '.cs', 'Ruby': '.rb', 'PHP': '.php', 'Kotlin': '.kt', 'Swift': '.swift', 'Dart': '.dart', 'Scala': '.scala', 'Perl': '.pl', 'R': '.r', 'MATLAB': '.m', 'Lua': '.lua', 'Haskell': '.hs', 'Elixir': '.ex', 'Shell/Bash': '.sh', 'PowerShell': '.ps1', 'SQL': '.sql', 'GraphQL': '.graphql', 'HTML/CSS': '.html', 'SASS/SCSS': '.scss', 'React': '.jsx', 'Node.js': '.js', 'Angular': '.ts', 'Vue.js': '.vue', 'Next.js': '.jsx', 'Svelte': '.svelte', 'Terraform': '.tf', 'Docker': '.dockerfile', 'YAML': '.yml', 'JSON': '.json', 'XML': '.xml', 'Markdown': '.md' }[asset.lang] || '.txt'
        : '.md';
      filename = (asset.name || 'asset').replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase() + ext;
    }
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
    if (!asset?.code) return;
    navigator.clipboard.writeText(asset.code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  if (loading) {
    return (
      <>
        <Header title="Asset Details" onMenuClick={onMenuClick} />
        <div className="p-6 flex items-center justify-center min-h-[40vh]">
          <Loader2 className="w-8 h-8 animate-spin text-primary-500" />
        </div>
      </>
    );
  }

  if (!asset) {
    return (
      <>
        <Header title="Asset Details" onMenuClick={onMenuClick} />
        <div className="p-6 text-center text-gray-500 dark:text-slate-400">Asset not found.</div>
      </>
    );
  }

  return (
    <>
      <Header title="Asset Details" onMenuClick={onMenuClick} />

      <div className="p-6 max-w-5xl space-y-6">
        {/* Back button */}
        <Link to="/browse" className="inline-flex items-center gap-2 text-sm text-gray-500 dark:text-slate-400 hover:text-primary-600 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Browse
        </Link>

        {/* Asset Header */}
        <div className="relative overflow-hidden bg-white dark:bg-slate-800 rounded-2xl border border-gray-200/80 dark:border-slate-700 p-6 shadow-sm">
          <div className="absolute top-0 right-0 w-56 h-56 bg-gradient-to-br from-primary-500/[0.04] to-accent-500/[0.04] rounded-full -translate-y-1/2 translate-x-1/3" />
          <div className="absolute bottom-0 left-0 w-32 h-32 bg-gradient-to-tr from-primary-500/[0.02] to-transparent rounded-full translate-y-1/2 -translate-x-1/4" />
          <div className="flex items-start justify-between relative">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <h1 className="text-2xl font-black text-gray-900 dark:text-white tracking-tight">{asset.name}</h1>
                <span className={`text-xs font-semibold px-2.5 py-0.5 rounded-full ${
                  asset.status === 'Approved' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400' : 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400'
                }`}>
                  <CheckCircle2 className="w-3 h-3 inline mr-1" />
                  {asset.status}
                </span>
                {asset.reusabilityLevel && <ReusabilityBadge level={asset.reusabilityLevel} score={asset.score} />}
              </div>
              <p className="text-gray-600 dark:text-slate-300 max-w-2xl leading-relaxed">{asset.desc}</p>
              <div className="flex flex-wrap items-center gap-3 mt-4 text-sm text-gray-500 dark:text-slate-400">
                <span className="flex items-center gap-1"><User className="w-4 h-4" />{asset.author}</span>
                <span className="flex items-center gap-1"><GitBranch className="w-4 h-4" />v{asset.version}</span>
                <span className="flex items-center gap-1"><Clock className="w-4 h-4" />{asset.createdAt ? new Date(asset.createdAt).toLocaleDateString() : ''}</span>
                {asset.type === 'Code' ? (
                  <span className="flex items-center gap-1"><Code2 className="w-4 h-4" />{asset.lang}</span>
                ) : (
                  <span className="flex items-center gap-1"><FileText className="w-4 h-4" />{asset.lang || 'Document'}</span>
                )}
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button onClick={handleDownload} className="px-4 py-2.5 bg-gradient-to-r from-primary-500 to-primary-600 text-white rounded-xl text-sm font-semibold hover:from-primary-600 hover:to-primary-700 transition-all flex items-center gap-2 shadow-lg shadow-primary-500/20 hover:shadow-primary-500/30 hover:scale-[1.02] active:scale-[0.98]">
                <Download className="w-4 h-4" /> Download
              </button>
              <button onClick={handleFavorite} className={`px-4 py-2.5 border rounded-xl text-sm font-semibold transition-all flex items-center gap-2 hover:scale-[1.02] active:scale-[0.98] ${
                isFavorited
                  ? 'border-pink-300 dark:border-pink-800 bg-pink-50 dark:bg-pink-900/20 text-pink-600 dark:text-pink-400'
                  : 'border-gray-200 dark:border-slate-600 text-gray-700 dark:text-slate-300 hover:bg-gray-50 dark:hover:bg-slate-700'
              }`}>
                <Heart className={`w-4 h-4 ${isFavorited ? 'fill-pink-500 text-pink-500' : ''}`} />
                {isFavorited ? 'Saved' : 'Save'} {favCount > 0 && `(${favCount})`}
              </button>
              <button onClick={handleExportDoc} className="px-4 py-2.5 border border-gray-200 dark:border-slate-600 text-gray-700 dark:text-slate-300 rounded-xl text-sm font-semibold hover:bg-gray-50 dark:hover:bg-slate-700 transition-all flex items-center gap-2 hover:scale-[1.02] active:scale-[0.98]" title="Export Documentation">
                <FileDown className="w-4 h-4" /> Export
              </button>
              {isAdmin && (
                <button onClick={() => setShowDeleteConfirm(true)} className="px-4 py-2.5 border border-red-200 dark:border-red-800/50 text-red-600 dark:text-red-400 rounded-xl text-sm font-semibold hover:bg-red-50 dark:hover:bg-red-900/20 transition-all flex items-center gap-2 hover:scale-[1.02] active:scale-[0.98]">
                  <Trash2 className="w-4 h-4" /> Delete
                </button>
              )}
            </div>
          </div>

          {/* Stats + Rating */}
          <div className="flex items-center gap-6 mt-5 pt-5 border-t border-gray-100 dark:border-slate-700">
            {/* Star Rating */}
            <div className="flex items-center gap-1.5">
              {[1, 2, 3, 4, 5].map(s => (
                <button
                  key={s}
                  onClick={() => handleRate(s)}
                  onMouseEnter={() => setHoverRating(s)}
                  onMouseLeave={() => setHoverRating(0)}
                  className="p-0.5 transition-transform hover:scale-110"
                >
                  <Star className={`w-5 h-5 transition-colors ${
                    s <= (hoverRating || userRating)
                      ? 'text-amber-400 fill-amber-400'
                      : s <= avgRating
                      ? 'text-amber-300 fill-amber-200'
                      : 'text-gray-300 dark:text-slate-600'
                  }`} />
                </button>
              ))}
              <span className="text-sm font-bold text-gray-700 dark:text-slate-300 ml-1">{avgRating > 0 ? avgRating : '—'}</span>
              <span className="text-xs text-gray-400 dark:text-slate-500">({ratingCount})</span>
            </div>
            <span className="flex items-center gap-1.5 text-sm text-gray-600 dark:text-slate-400">
              <Download className="w-4 h-4 text-gray-400 dark:text-slate-500" /> {asset.downloads} downloads
            </span>
            <span className="flex items-center gap-1.5 text-sm text-gray-600 dark:text-slate-400">
              <Heart className={`w-4 h-4 ${favCount > 0 ? 'text-pink-400 fill-pink-400' : 'text-gray-400 dark:text-slate-500'}`} /> {favCount} saved
            </span>
          </div>

          {/* Tags */}
          <div className="flex items-center gap-2 mt-4 flex-wrap">
            <Tag className="w-4 h-4 text-gray-400 dark:text-slate-500" />
            {(asset.tags || []).map(tag => (
              <span key={tag} className="bg-gray-100 dark:bg-slate-700 text-gray-600 dark:text-slate-300 text-xs px-2.5 py-1 rounded-full">{tag}</span>
            ))}
            {asset.project && (
              <span className="bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-xs px-2.5 py-1 rounded-full font-semibold flex items-center gap-1">
                <Car className="w-3 h-3" /> {asset.project}
              </span>
            )}
            {asset.ecuType && (
              <span className="bg-cyan-100 dark:bg-cyan-900/30 text-cyan-700 dark:text-cyan-400 text-xs px-2.5 py-1 rounded-full font-semibold flex items-center gap-1">
                <Cpu className="w-3 h-3" /> {asset.ecuType}
              </span>
            )}
          </div>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Content Preview - Code or Document */}
          <div className="lg:col-span-2 space-y-4">
            {/* Main content panel */}
            <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 overflow-hidden shadow-sm">
              {asset.type === 'Code' ? (
                <>
                  <div className="flex items-center justify-between px-5 py-3.5 border-b border-gray-100 dark:border-slate-700 bg-gradient-to-r from-gray-50 to-gray-100/50 dark:from-slate-800/80 dark:to-slate-800">
                    <span className="text-sm font-bold text-gray-700 dark:text-slate-300 flex items-center gap-2">
                      <Code2 className="w-4 h-4 text-primary-500" /> Code Preview
                      {asset.originalFileName && <span className="text-xs font-normal text-gray-400 dark:text-slate-500 ml-2">({asset.originalFileName})</span>}
                    </span>
                    <button onClick={handleCopy} className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-slate-400 hover:text-primary-600 transition-colors">
                      {copied ? <><CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy</>}
                    </button>
                  </div>
                  <pre className="p-5 code-block text-gray-100 text-sm font-mono overflow-x-auto leading-relaxed max-h-[600px] overflow-y-auto">
                    <code>{asset.code || 'No code content available.'}</code>
                  </pre>
                </>
              ) : (
                <>
                  <div className="flex items-center justify-between px-5 py-3.5 border-b border-gray-100 dark:border-slate-700 bg-gradient-to-r from-purple-50/50 to-gray-50 dark:from-purple-900/10 dark:to-slate-800">
                    <span className="text-sm font-bold text-gray-700 dark:text-slate-300 flex items-center gap-2">
                      <FileText className="w-4 h-4 text-purple-500" /> Document Content
                      {asset.originalFileName && <span className="text-xs font-normal text-gray-400 dark:text-slate-500 ml-2">({asset.originalFileName})</span>}
                    </span>
                    {asset.code && !asset.storedFileName && (
                      <button onClick={handleCopy} className="flex items-center gap-1.5 text-xs text-gray-500 dark:text-slate-400 hover:text-primary-600 transition-colors">
                        {copied ? <><CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Copied!</> : <><Copy className="w-3.5 h-3.5" /> Copy</>}
                      </button>
                    )}
                  </div>
                  {asset.storedFileName && asset.originalFileName?.toLowerCase().endsWith('.pdf') ? (
                    <div className="w-full" style={{ height: '700px' }}>
                      <iframe
                        src={`http://${window.location.hostname}:3001/api/assets/${asset.id}/file`}
                        className="w-full h-full border-0"
                        title="PDF Preview"
                      />
                    </div>
                  ) : (
                    <div className="p-5 prose prose-sm dark:prose-invert max-w-none text-gray-700 dark:text-slate-300 leading-relaxed whitespace-pre-wrap max-h-[600px] overflow-y-auto">
                      {asset.code || 'No document content available.'}
                    </div>
                  )}
                </>
              )}
            </div>

            {/* Description panel (separate from content) */}
            {asset.desc && (
              <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 overflow-hidden shadow-sm">
                <div className="px-5 py-3.5 border-b border-gray-100 dark:border-slate-700 bg-gray-50/50 dark:bg-slate-800/80">
                  <span className="text-sm font-bold text-gray-700 dark:text-slate-300">Description</span>
                </div>
                <div className="p-5 text-sm text-gray-700 dark:text-slate-300 leading-relaxed whitespace-pre-wrap">
                  {asset.desc}
                </div>
              </div>
            )}
          </div>

          {/* Quality Score */}
          <div className="space-y-4">
            <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 p-5 shadow-sm">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg bg-primary-100 dark:bg-primary-900/30 flex items-center justify-center">
                  <Shield className="w-4 h-4 text-primary-600" />
                </div>
                <h3 className="font-bold text-gray-900 dark:text-white">Quality Report</h3>
              </div>
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-sm text-gray-600 dark:text-slate-400">Reusability Score</span>
                  <span className="text-sm font-bold text-emerald-600">{asset.score || 'N/A'}%</span>
                </div>
                {asset.score && (
                  <div className="w-full bg-gray-200 dark:bg-slate-700 rounded-full h-2">
                    <div className="bg-emerald-500 h-2 rounded-full" style={{ width: `${asset.score}%` }} />
                  </div>
                )}
                <div className="flex items-center justify-between pt-2">
                  <span className="text-sm text-gray-600 dark:text-slate-400">Type</span>
                  <span className="text-sm font-bold text-primary-600">{asset.type}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-gray-600 dark:text-slate-400">Category</span>
                  <span className="text-sm font-bold text-primary-600">{asset.category}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-sm text-gray-600 dark:text-slate-400">Version</span>
                  <span className="text-sm font-bold text-emerald-600">{asset.version || '1.0.0'}</span>
                </div>
              </div>
            </div>

            {asset.type === 'Code' && asset.code && (
            <div className="bg-white dark:bg-slate-800 rounded-xl border border-gray-200 dark:border-slate-700 p-5">
              <h3 className="font-semibold text-gray-900 dark:text-white mb-3 flex items-center gap-2"><Code2 className="w-4 h-4 text-primary-500" /> Quick Usage</h3>
              <pre className="bg-gray-50 dark:bg-slate-900 rounded-lg p-3 text-xs text-gray-700 dark:text-slate-300 font-mono overflow-x-auto whitespace-pre-wrap max-h-48">
{asset.code.split('\n').slice(0, 8).join('\n')}{asset.code.split('\n').length > 8 ? '\n// ...' : ''}
              </pre>
            </div>
            )}

            {/* MISRA & Safety Compliance */}
            {asset.type === 'Code' && asset.code && (
            <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 p-5 shadow-sm">
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-lg bg-amber-100 dark:bg-amber-900/30 flex items-center justify-center">
                    <ShieldCheck className="w-4 h-4 text-amber-600 dark:text-amber-400" />
                  </div>
                  <h3 className="font-bold text-gray-900 dark:text-white text-sm">MISRA & Safety</h3>
                </div>
                {!misraResult && (
                  <button
                    onClick={handleMISRACheck}
                    disabled={misraLoading}
                    className="px-3 py-1.5 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 rounded-lg text-xs font-semibold hover:bg-amber-200 dark:hover:bg-amber-900/50 transition-colors flex items-center gap-1.5 disabled:opacity-50"
                  >
                    {misraLoading ? <><Loader2 className="w-3 h-3 animate-spin" /> Analyzing...</> : <><ShieldCheck className="w-3 h-3" /> Run Check</>}
                  </button>
                )}
              </div>

              {misraLoading && (
                <div className="flex items-center justify-center py-6">
                  <div className="text-center">
                    <Loader2 className="w-6 h-6 animate-spin text-amber-500 mx-auto mb-2" />
                    <p className="text-xs text-gray-500 dark:text-slate-400">AI analyzing MISRA compliance...</p>
                  </div>
                </div>
              )}

              {!misraResult && !misraLoading && (
                <p className="text-xs text-gray-500 dark:text-slate-400">Click "Run Check" to analyze this code for MISRA C/C++ compliance, ASIL level, and ISO 26262 safety issues.</p>
              )}

              {misraResult && !misraResult.error && (
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <div className={`px-2.5 py-1 rounded-lg text-xs font-bold ${
                      misraResult.asilLevel === 'D' ? 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400' :
                      misraResult.asilLevel === 'C' ? 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400' :
                      misraResult.asilLevel === 'B' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' :
                      misraResult.asilLevel === 'A' ? 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400' :
                      'bg-gray-100 text-gray-700 dark:bg-slate-700 dark:text-slate-300'
                    }`}>
                      ASIL {misraResult.asilLevel || 'QM'}
                    </div>
                    <div className={`px-2.5 py-1 rounded-lg text-xs font-bold ${
                      misraResult.overallCompliance === 'Compliant' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400' :
                      misraResult.overallCompliance === 'Minor Issues' ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400' :
                      'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                    }`}>
                      {misraResult.overallCompliance}
                    </div>
                  </div>

                  <div className="flex items-center justify-between">
                    <span className="text-xs text-gray-500 dark:text-slate-400">MISRA Score</span>
                    <span className="text-xs font-bold text-amber-600">{misraResult.misraScore}/100</span>
                  </div>
                  <div className="w-full bg-gray-200 dark:bg-slate-700 rounded-full h-1.5">
                    <div className={`h-1.5 rounded-full ${misraResult.misraScore >= 80 ? 'bg-emerald-500' : misraResult.misraScore >= 50 ? 'bg-amber-500' : 'bg-red-500'}`} style={{ width: `${misraResult.misraScore}%` }} />
                  </div>

                  {misraResult.violations?.length > 0 && (
                    <div className="mt-2">
                      <p className="text-[10px] font-bold text-gray-400 dark:text-slate-500 uppercase mb-1.5">Violations ({misraResult.violations.length})</p>
                      <div className="space-y-1.5 max-h-40 overflow-y-auto">
                        {misraResult.violations.slice(0, 5).map((v, i) => (
                          <div key={i} className="p-2 rounded-lg bg-red-50/50 dark:bg-red-900/10 border border-red-100 dark:border-red-900/20">
                            <div className="flex items-center gap-1.5">
                              <ShieldAlert className="w-3 h-3 text-red-500 shrink-0" />
                              <span className="text-[10px] font-bold text-red-700 dark:text-red-400">{v.rule}</span>
                              <span className={`text-[9px] px-1 py-0.5 rounded font-medium ${v.severity === 'Mandatory' ? 'bg-red-200 text-red-800' : v.severity === 'Required' ? 'bg-amber-200 text-amber-800' : 'bg-gray-200 text-gray-700'}`}>{v.severity}</span>
                            </div>
                            <p className="text-[10px] text-gray-600 dark:text-slate-400 mt-0.5">{v.description}</p>
                            {v.fix && <p className="text-[10px] text-emerald-600 dark:text-emerald-400 mt-0.5">Fix: {v.fix}</p>}
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {misraResult.recommendations?.length > 0 && (
                    <div className="mt-1">
                      <p className="text-[10px] font-bold text-gray-400 dark:text-slate-500 uppercase mb-1">Recommendations</p>
                      {misraResult.recommendations.slice(0, 3).map((r, i) => (
                        <p key={i} className="text-[10px] text-gray-600 dark:text-slate-400 flex items-start gap-1 mb-0.5">
                          <CheckCircle2 className="w-3 h-3 text-emerald-500 shrink-0 mt-0.5" />{r}
                        </p>
                      ))}
                    </div>
                  )}

                  <button onClick={handleMISRACheck} className="w-full mt-2 text-[10px] text-center text-amber-600 dark:text-amber-400 hover:underline">Re-run analysis</button>
                </div>
              )}
            </div>
            )}
          </div>
        </div>

        {/* Comments Section */}
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-gray-200/80 dark:border-slate-700 overflow-hidden shadow-sm">
          <div className="px-5 py-4 border-b border-gray-100 dark:border-slate-700 flex items-center gap-2">
            <MessageSquare className="w-5 h-5 text-primary-500" />
            <h3 className="font-bold text-gray-900 dark:text-white">Discussion</h3>
            <span className="text-xs text-gray-400 dark:text-slate-500 bg-gray-100 dark:bg-slate-700 px-2 py-0.5 rounded-full">{comments.length}</span>
          </div>

          {/* Add Comment */}
          <div className="p-4 border-b border-gray-100 dark:border-slate-700">
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-500 to-accent-500 flex items-center justify-center text-white text-xs font-bold shrink-0">
                {user?.initials || 'U'}
              </div>
              <div className="flex-1 relative">
                <textarea
                  value={commentText}
                  onChange={e => setCommentText(e.target.value)}
                  placeholder="Add a comment..."
                  rows={2}
                  className="w-full px-4 py-3 bg-gray-50 dark:bg-slate-900 border border-gray-200 dark:border-slate-600 rounded-xl text-sm text-gray-900 dark:text-white placeholder:text-gray-400 dark:placeholder:text-slate-500 focus:outline-none focus:ring-2 focus:ring-primary-500/30 focus:border-primary-400 resize-none"
                  onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handlePostComment(); } }}
                />
                <button
                  onClick={handlePostComment}
                  disabled={!commentText.trim() || postingComment}
                  className="absolute bottom-2 right-2 p-2 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  {postingComment ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                </button>
              </div>
            </div>
          </div>

          {/* Comments List */}
          <div className="divide-y divide-gray-100 dark:divide-slate-700 max-h-96 overflow-y-auto">
            {comments.length === 0 ? (
              <div className="p-8 text-center text-sm text-gray-400 dark:text-slate-500">
                No comments yet. Be the first to share your thoughts!
              </div>
            ) : (
              comments.map(c => (
                <div key={c.id} className="p-4 hover:bg-gray-50/50 dark:hover:bg-slate-800/50 transition-colors group">
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-gradient-to-br from-gray-400 to-gray-500 dark:from-slate-500 dark:to-slate-600 flex items-center justify-center text-white text-xs font-bold shrink-0">
                      {(c.user || 'U').substring(0, 2).toUpperCase()}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-semibold text-gray-900 dark:text-white">{c.user}</span>
                        <span className="text-xs text-gray-400 dark:text-slate-500">
                          {c.timestamp ? new Date(c.timestamp).toLocaleString() : ''}
                        </span>
                        {(isAdmin || c.user === user?.username) && (
                          <button
                            onClick={() => handleDeleteComment(c.id)}
                            className="ml-auto p-1 text-gray-300 hover:text-red-500 dark:text-slate-600 dark:hover:text-red-400 opacity-0 group-hover:opacity-100 transition-all"
                            title="Delete comment"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>
                      <p className="text-sm text-gray-600 dark:text-slate-300 mt-1 whitespace-pre-wrap">{c.text}</p>
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Delete Confirmation Modal */}
      {showDeleteConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 animate-fade-in">
          <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={() => setShowDeleteConfirm(false)} />
          <div className="relative bg-white dark:bg-slate-800 rounded-2xl border border-gray-200 dark:border-slate-700 shadow-2xl w-full max-w-sm animate-scale-in">
            <div className="p-6 text-center">
              <div className="w-14 h-14 rounded-2xl bg-red-50 dark:bg-red-900/20 flex items-center justify-center mx-auto mb-4">
                <AlertTriangle className="w-7 h-7 text-red-500" />
              </div>
              <h3 className="font-bold text-lg text-gray-900 dark:text-white">Delete Asset?</h3>
              <p className="text-sm text-gray-500 dark:text-slate-400 mt-2">
                Are you sure you want to delete <strong className="text-gray-700 dark:text-slate-300">{asset.name}</strong>? This action cannot be undone.
              </p>
            </div>
            <div className="flex items-center gap-3 px-6 py-4 border-t border-gray-100 dark:border-slate-700 bg-gray-50/50 dark:bg-slate-800/50 rounded-b-2xl">
              <button
                onClick={() => setShowDeleteConfirm(false)}
                className="flex-1 py-2.5 text-sm font-semibold text-gray-600 dark:text-slate-400 bg-white dark:bg-slate-700 border border-gray-200 dark:border-slate-600 rounded-xl hover:bg-gray-50 dark:hover:bg-slate-600 transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleDelete}
                disabled={deleting}
                className="flex-1 py-2.5 bg-gradient-to-r from-red-500 to-rose-500 text-white text-sm font-semibold rounded-xl hover:from-red-600 hover:to-rose-600 transition-all disabled:opacity-50 shadow-md shadow-red-500/20 flex items-center justify-center gap-2"
              >
                {deleting ? <Loader2 className="w-4 h-4 animate-spin" /> : <><Trash2 className="w-4 h-4" /> Delete</>}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
